language: php
php:
  - 7.0
  - 7.1 - ./vendon/bin/phpunit
matrix:
  allow_failures:
    - php: nightly
install:
 - composer self-update
 - composer install --no-interaction --dev
before_script:
  - mkdir -p build/
  - mkdir -p build/logs
script:
 - ./vendon/bin/phpunit
after_script:
 - php vendor/bin/coveralls -v
 - php vendor/bin/codacycoverage clover build/logs/clover.xml
